// gosq-codegen introspects a database schema and generates type-safe Go
// table and field definitions for use with github.com/libliflin/gosq.
//
// Usage:
//
//	gosq-codegen -dsn "postgres://user:pass@localhost:5432/mydb" -out schema/
//
// The generated code uses gosq's NewTable and NewField constructors, giving
// you compile-time column references instead of raw strings. The output looks
// like:
//
//	// Code generated by gosq-codegen; DO NOT EDIT.
//
//	package schema
//
//	import . "github.com/libliflin/gosq"
//
//	var Users = NewTable("users")
//
//	var (
//		UsersID    = NewField("users.id")
//		UsersName  = NewField("users.name")
//		UsersEmail = NewField("users.email")
//	)
package main

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"go/token"
	"os"
	"path/filepath"
	"runtime/debug"
	"time"

	"github.com/libliflin/gosq-codegen/internal/codegen"
	"github.com/libliflin/gosq-codegen/internal/introspect"
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/lib/pq"
	_ "modernc.org/sqlite"
)

func main() {
	driver := flag.String("driver", "postgres", "database driver: postgres, cockroach, mysql, mariadb, or sqlite")
	dsn := flag.String("dsn", "", "database connection string (required)")
	out := flag.String("out", "schema/", "output directory")
	pkg := flag.String("pkg", "schema", "Go package name for generated file")
	schema := flag.String("schema", "public", "schema to introspect (MySQL: use database name; SQLite: stored as Table.Schema, not used for filtering)")
	dotImport := flag.Bool("dot-import", true, "use dot-import for gosq (import . \"github.com/libliflin/gosq\")")
	version := flag.Bool("version", false, "print version and exit")
	flag.Parse()

	if *version {
		bi, ok := debug.ReadBuildInfo()
		if ok && bi.Main.Version != "" {
			fmt.Println(bi.Main.Version)
		} else {
			fmt.Println("(devel)")
		}
		return
	}

	if !token.IsIdentifier(*pkg) || token.IsKeyword(*pkg) {
		fmt.Fprintf(os.Stderr, "gosq-codegen: invalid package name %q\n", *pkg)
		os.Exit(1)
	}

	var dialect introspect.Dialect
	// sqlDriverName is the driver name passed to sql.Open. It differs from
	// *driver when the user selects "cockroach" or "mariadb": those databases
	// are wire-compatible with postgres and mysql respectively, so we open them
	// with the registered driver name ("postgres" and "mysql").
	sqlDriverName := *driver
	switch *driver {
	case "postgres":
		dialect = introspect.DialectPostgres
	case "cockroach":
		dialect = introspect.DialectPostgres
		sqlDriverName = "postgres"
	case "mysql":
		dialect = introspect.DialectMySQL
	case "mariadb":
		dialect = introspect.DialectMySQL
		sqlDriverName = "mysql"
	case "sqlite":
		dialect = introspect.DialectSQLite
	default:
		fmt.Fprintf(os.Stderr, "gosq-codegen: unsupported driver %q (supported: postgres, cockroach, mysql, mariadb, sqlite)\n", *driver)
		os.Exit(1)
	}

	if *dsn == "" {
		fmt.Fprintln(os.Stderr, "gosq-codegen: -dsn is required")
		flag.Usage()
		os.Exit(1)
	}

	db, err := sql.Open(sqlDriverName, *dsn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gosq-codegen: open db: %v\n", err)
		os.Exit(1)
	}
	defer db.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	tables, err := introspect.Tables(ctx, db, *schema, dialect)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gosq-codegen: introspect: %v\n", err)
		os.Exit(1)
	}

	if len(tables) == 0 {
		fmt.Fprintf(os.Stderr, "gosq-codegen: warning: no tables found in schema %q\n", *schema)
	}

	src, err := codegen.Generate(tables, codegen.Config{Package: *pkg, DotImport: *dotImport})
	if err != nil {
		fmt.Fprintf(os.Stderr, "gosq-codegen: generate: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(*out, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "gosq-codegen: mkdir %s: %v\n", *out, err)
		os.Exit(1)
	}

	outFile := filepath.Join(*out, *pkg+".go")
	if err := os.WriteFile(outFile, src, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gosq-codegen: write %s: %v\n", outFile, err)
		os.Exit(1)
	}

	noun := "tables"
	if len(tables) == 1 {
		noun = "table"
	}
	fmt.Fprintf(os.Stdout, "wrote %s (%d %s)\n", outFile, len(tables), noun)
}
