// Package codegen renders Go source files from introspected schema metadata.
// The output uses gosq's NewTable and NewField constructors.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/libliflin/gosq-codegen/internal/introspect"
)

// Config controls code generation output.
type Config struct {
	// Package is the Go package name for generated files (default: "schema").
	Package string

	// DotImport controls whether to use dot-import for gosq.
	// When true:  import . "github.com/libliflin/gosq"
	// When false: import "github.com/libliflin/gosq"
	DotImport bool
}

// Generate produces Go source code for the given tables.
func Generate(tables []introspect.Table, cfg Config) ([]byte, error) {
	if cfg.Package == "" {
		cfg.Package = "schema"
	}

	sorted := make([]introspect.Table, len(tables))
	copy(sorted, tables)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	// Detect identifier collisions and blank identifiers before rendering.
	tableIdents := make(map[string]string)  // ident → original table name
	fieldIdents := make(map[string][2]string) // full field ident → [table, column]
	for _, tbl := range sorted {
		ident := toExported(tbl.Name)
		if ident == "_" {
			return nil, fmt.Errorf("table %q produces blank identifier %q; it cannot be referenced in Go", tbl.Name, ident)
		}
		if prev, ok := tableIdents[ident]; ok {
			return nil, fmt.Errorf("tables %q and %q both produce identifier %q", prev, tbl.Name, ident)
		}
		if prev, ok := fieldIdents[ident]; ok {
			return nil, fmt.Errorf("table %q and field %q.%q both produce identifier %q", tbl.Name, prev[0], prev[1], ident)
		}
		tableIdents[ident] = tbl.Name

		colIdents := make(map[string]string) // ident → original column name
		for _, col := range tbl.Columns {
			colIdent := toExported(col.Name)
			if prev, ok := colIdents[colIdent]; ok {
				return nil, fmt.Errorf("columns %q and %q in table %q both produce identifier %q", prev, col.Name, tbl.Name, colIdent)
			}
			colIdents[colIdent] = col.Name

			fieldIdent := ident + colIdent
			if prev, ok := fieldIdents[fieldIdent]; ok {
				return nil, fmt.Errorf("field %q.%q and %q.%q both produce identifier %q", prev[0], prev[1], tbl.Name, col.Name, fieldIdent)
			}
			if prevTable, ok := tableIdents[fieldIdent]; ok {
				return nil, fmt.Errorf("field %q.%q and table %q both produce identifier %q", tbl.Name, col.Name, prevTable, fieldIdent)
			}
			fieldIdents[fieldIdent] = [2]string{tbl.Name, col.Name}
		}
	}

	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage %s\n\n", cfg.Package)

	if len(sorted) > 0 {
		if cfg.DotImport {
			fmt.Fprintf(&buf, "import . \"github.com/libliflin/gosq\"\n\n")
		} else {
			fmt.Fprintf(&buf, "import \"github.com/libliflin/gosq\"\n\n")
		}
	}

	for _, tbl := range sorted {
		tableIdent := toExported(tbl.Name)
		if cfg.DotImport {
			fmt.Fprintf(&buf, "var %s = NewTable(%q)\n\n", tableIdent, tbl.Name)
		} else {
			fmt.Fprintf(&buf, "var %s = gosq.NewTable(%q)\n\n", tableIdent, tbl.Name)
		}

		if len(tbl.Columns) > 0 {
			fmt.Fprintf(&buf, "var (\n")
			for _, col := range tbl.Columns {
				fieldIdent := tableIdent + toExported(col.Name)
				if cfg.DotImport {
					fmt.Fprintf(&buf, "\t%s = NewField(%q)\n", fieldIdent, tbl.Name+"."+col.Name)
				} else {
					fmt.Fprintf(&buf, "\t%s = gosq.NewField(%q)\n", fieldIdent, tbl.Name+"."+col.Name)
				}
			}
			fmt.Fprintf(&buf, ")\n\n")
		}
	}

	src := bytes.TrimRight(buf.Bytes(), "\n")
	src = append(src, '\n')

	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w", err)
	}
	return formatted, nil
}

// goInitialisms maps lowercase words to their idiomatic Go uppercase form.
var goInitialisms = map[string]string{
	"id":    "ID",
	"url":   "URL",
	"uri":   "URI",
	"http":  "HTTP",
	"https": "HTTPS",
	"sql":   "SQL",
	"api":   "API",
	"uid":   "UID",
	"uuid":  "UUID",
	"ip":    "IP",
	"io":    "IO",
	"cpu":   "CPU",
	"xml":   "XML",
	"json":  "JSON",
	"rpc":   "RPC",
	"tls":   "TLS",
	"ttl":   "TTL",
}

// toExported converts a snake_case database identifier to an exported Go identifier.
// If the result would start with a digit, it is prefixed with "_".
// If the result would be empty (e.g. all underscores), it is replaced with "_".
func toExported(name string) string {
	parts := strings.Split(name, "_")
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		if upper, ok := goInitialisms[strings.ToLower(part)]; ok {
			b.WriteString(upper)
		} else {
			runes := []rune(part)
			b.WriteString(strings.ToUpper(string(runes[:1])) + string(runes[1:]))
		}
	}
	result := b.String()
	if result == "" {
		return "_"
	}
	if result[0] >= '0' && result[0] <= '9' {
		return "_" + result
	}
	return result
}
