package codegen

import (
	"bytes"
	"strings"
	"testing"

	"github.com/libliflin/gosq-codegen/internal/introspect"
)

func TestGenerateEmpty(t *testing.T) {
	out, err := Generate(nil, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n"
	if string(out) != want {
		t.Errorf("output mismatch\ngot:  %q\nwant: %q", string(out), want)
	}
}

func TestGenerateDotImportFalse(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "users",
			Columns: []introspect.Column{
				{Name: "id", DataType: "integer", IsNullable: false, OrdinalPos: 1},
			},
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: false})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport \"github.com/libliflin/gosq\"\n\nvar Users = gosq.NewTable(\"users\")\n\nvar (\n\tUsersID = gosq.NewField(\"users.id\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateDigitLeadingColumn(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "accounts",
			Columns: []introspect.Column{
				{Name: "2fa_enabled", DataType: "boolean", IsNullable: false, OrdinalPos: 1},
			},
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Accounts = NewTable(\"accounts\")\n\nvar (\n\tAccounts_2faEnabled = NewField(\"accounts.2fa_enabled\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateAllUnderscoreColumn(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "items",
			Columns: []introspect.Column{
				{Name: "___", DataType: "text", IsNullable: false, OrdinalPos: 1},
			},
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Items = NewTable(\"items\")\n\nvar (\n\tItems_ = NewField(\"items.___\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateTableNoColumns(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema:  "public",
			Name:    "events",
			Columns: nil,
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Events = NewTable(\"events\")\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateMultipleTablesOrdered(t *testing.T) {
	// Tables deliberately provided out of alphabetical order to verify sort.
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "orders",
			Columns: []introspect.Column{
				{Name: "id", DataType: "integer", IsNullable: false, OrdinalPos: 1},
			},
		},
		{
			Schema: "public",
			Name:   "accounts",
			Columns: []introspect.Column{
				{Name: "id", DataType: "integer", IsNullable: false, OrdinalPos: 1},
			},
		},
	}

	// Empty Package — exercises the default-package fallback.
	got, err := Generate(tables, Config{DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Accounts = NewTable(\"accounts\")\n\nvar (\n\tAccountsID = NewField(\"accounts.id\")\n)\n\nvar Orders = NewTable(\"orders\")\n\nvar (\n\tOrdersID = NewField(\"orders.id\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateTableCollision(t *testing.T) {
	// "user_data" and "user__data" both map to "UserData" — should error.
	tables := []introspect.Table{
		{Schema: "public", Name: "user_data"},
		{Schema: "public", Name: "user__data"},
	}
	_, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err == nil {
		t.Fatal("expected error for colliding table identifiers, got nil")
	}
}

func TestGenerateBlankIdentifierTable(t *testing.T) {
	// A table named "_" (or any all-underscore name) produces toExported → "_",
	// which is the Go blank identifier. var _ = NewTable("_") compiles but the
	// value is discarded and the table can never be referenced. Generate should
	// error rather than silently emit dead code.
	for _, name := range []string{"_", "__", "___"} {
		tables := []introspect.Table{
			{Schema: "public", Name: name},
		}
		_, err := Generate(tables, Config{Package: "schema", DotImport: true})
		if err == nil {
			t.Errorf("expected error for table %q producing blank identifier, got nil", name)
		}
	}
}

func TestGenerateTableFieldCollision(t *testing.T) {
	// Table "users_id" produces table ident "UsersID".
	// Table "users" with column "id" produces field ident "UsersID".
	// Both would emit "var UsersID = ..." — a redeclaration error in the generated file.
	tables := []introspect.Table{
		{Schema: "public", Name: "users", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
		}},
		{Schema: "public", Name: "users_id"},
	}
	_, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err == nil {
		t.Fatal("expected error for table-field identifier collision, got nil")
	}
}

func TestGenerateCrossTableFieldCollision(t *testing.T) {
	// Table "a" with column "b_c" produces field var "A"+"BC" = "ABC".
	// Table "a_b" with column "c" produces field var "AB"+"C" = "ABC".
	// Table collision detection passes (A ≠ AB), within-table column detection
	// passes (each table has one column), but the full field identifiers collide.
	tables := []introspect.Table{
		{Schema: "public", Name: "a", Columns: []introspect.Column{
			{Name: "b_c", DataType: "text", OrdinalPos: 1},
		}},
		{Schema: "public", Name: "a_b", Columns: []introspect.Column{
			{Name: "c", DataType: "text", OrdinalPos: 1},
		}},
	}
	_, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err == nil {
		t.Fatal("expected error for cross-table field identifier collision, got nil")
	}
}

func TestGenerateColumnCollision(t *testing.T) {
	// "my_field" and "my__field" both map to "MyField" — should error.
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "items",
			Columns: []introspect.Column{
				{Name: "my_field", DataType: "text", OrdinalPos: 1},
				{Name: "my__field", DataType: "text", OrdinalPos: 2},
			},
		},
	}
	_, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err == nil {
		t.Fatal("expected error for colliding column identifiers, got nil")
	}
}

func TestToExported(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		// Single words
		{"name", "Name"},
		{"id", "ID"},
		{"url", "URL"},
		{"uri", "URI"},
		{"uuid", "UUID"},
		{"ip", "IP"},
		{"api", "API"},
		{"sql", "SQL"},
		{"json", "JSON"},
		{"xml", "XML"},
		{"rpc", "RPC"},
		{"tls", "TLS"},
		{"ttl", "TTL"},
		{"http", "HTTP"},
		{"https", "HTTPS"},
		{"uid", "UID"},
		{"io", "IO"},
		{"cpu", "CPU"},

		// Compound snake_case
		{"user_id", "UserID"},
		{"url_params", "URLParams"},
		{"created_at", "CreatedAt"},
		{"updated_at", "UpdatedAt"},
		{"http_status_code", "HTTPStatusCode"},
		{"api_key", "APIKey"},
		{"oauth_token", "OauthToken"},

		// Edge cases
		{"2fa_enabled", "_2faEnabled"},
		{"___", "_"},
		{"", "_"},
		{"_leading", "Leading"},
		{"trailing_", "Trailing"},

		// Non-ASCII: column starting with a multi-byte UTF-8 character
		{"éclat", "Éclat"},
	}

	for _, tc := range tests {
		t.Run(tc.in, func(t *testing.T) {
			got := toExported(tc.in)
			if got != tc.want {
				t.Errorf("toExported(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestGenerateProductionScale(t *testing.T) {
	// Simulates a realistic production schema: 17 tables, 108 columns total.
	// Naming patterns include: common snake_case, digit-prefixed columns,
	// compound initialisations (http, url, tls, api, ip, uuid, id), long names,
	// and tables provided deliberately out of alphabetical order to exercise sort.
	// Verifies: no error, deterministic output, alphabetical table order,
	// correct identifiers for key naming patterns, expected table and field counts.
	tables := []introspect.Table{
		// Deliberately unordered to exercise alphabetical sort.
		{Schema: "public", Name: "users", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "email", DataType: "text", OrdinalPos: 2},
			{Name: "full_name", DataType: "text", OrdinalPos: 3},
			{Name: "password_hash", DataType: "text", OrdinalPos: 4},
			{Name: "is_active", DataType: "boolean", OrdinalPos: 5},
			{Name: "role", DataType: "text", OrdinalPos: 6},
			{Name: "last_login_at", DataType: "timestamptz", OrdinalPos: 7},
			{Name: "2fa_enabled", DataType: "boolean", OrdinalPos: 8},
		}},
		{Schema: "public", Name: "accounts", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "name", DataType: "text", OrdinalPos: 2},
			{Name: "owner_id", DataType: "integer", OrdinalPos: 3},
			{Name: "plan_id", DataType: "integer", OrdinalPos: 4},
			{Name: "created_at", DataType: "timestamptz", OrdinalPos: 5},
			{Name: "updated_at", DataType: "timestamptz", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "api_keys", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "account_id", DataType: "integer", OrdinalPos: 2},
			{Name: "key_hash", DataType: "text", OrdinalPos: 3},
			{Name: "expires_at", DataType: "timestamptz", OrdinalPos: 4},
			{Name: "is_active", DataType: "boolean", OrdinalPos: 5},
			{Name: "scopes", DataType: "text[]", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "audit_logs", Columns: []introspect.Column{
			{Name: "id", DataType: "bigint", OrdinalPos: 1},
			{Name: "table_name", DataType: "text", OrdinalPos: 2},
			{Name: "row_id", DataType: "integer", OrdinalPos: 3},
			{Name: "action", DataType: "text", OrdinalPos: 4},
			{Name: "performed_by", DataType: "integer", OrdinalPos: 5},
			{Name: "ip_addr", DataType: "inet", OrdinalPos: 6},
			{Name: "created_at", DataType: "timestamptz", OrdinalPos: 7},
		}},
		{Schema: "public", Name: "billing_plans", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "name", DataType: "text", OrdinalPos: 2},
			{Name: "price_cents", DataType: "integer", OrdinalPos: 3},
			{Name: "interval_days", DataType: "integer", OrdinalPos: 4},
			{Name: "is_active", DataType: "boolean", OrdinalPos: 5},
		}},
		{Schema: "public", Name: "campaigns", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "account_id", DataType: "integer", OrdinalPos: 2},
			{Name: "name", DataType: "text", OrdinalPos: 3},
			{Name: "status", DataType: "text", OrdinalPos: 4},
			{Name: "launched_at", DataType: "timestamptz", OrdinalPos: 5},
			{Name: "ended_at", DataType: "timestamptz", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "devices", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "user_id", DataType: "integer", OrdinalPos: 2},
			{Name: "device_uuid", DataType: "uuid", OrdinalPos: 3},
			{Name: "platform", DataType: "text", OrdinalPos: 4},
			{Name: "last_seen_at", DataType: "timestamptz", OrdinalPos: 5},
			{Name: "push_token", DataType: "text", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "email_templates", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "name", DataType: "text", OrdinalPos: 2},
			{Name: "subject", DataType: "text", OrdinalPos: 3},
			{Name: "html_body", DataType: "text", OrdinalPos: 4},
			{Name: "text_body", DataType: "text", OrdinalPos: 5},
			{Name: "created_at", DataType: "timestamptz", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "feature_flags", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "name", DataType: "text", OrdinalPos: 2},
			{Name: "enabled", DataType: "boolean", OrdinalPos: 3},
			{Name: "rollout_pct", DataType: "integer", OrdinalPos: 4},
			{Name: "updated_at", DataType: "timestamptz", OrdinalPos: 5},
		}},
		{Schema: "public", Name: "http_requests", Columns: []introspect.Column{
			{Name: "id", DataType: "bigint", OrdinalPos: 1},
			{Name: "method", DataType: "text", OrdinalPos: 2},
			{Name: "url_path", DataType: "text", OrdinalPos: 3},
			{Name: "status_code", DataType: "integer", OrdinalPos: 4},
			{Name: "duration_ms", DataType: "integer", OrdinalPos: 5},
			{Name: "user_agent", DataType: "text", OrdinalPos: 6},
			{Name: "created_at", DataType: "timestamptz", OrdinalPos: 7},
		}},
		{Schema: "public", Name: "invitations", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "email", DataType: "text", OrdinalPos: 2},
			{Name: "account_id", DataType: "integer", OrdinalPos: 3},
			{Name: "token", DataType: "text", OrdinalPos: 4},
			{Name: "sent_at", DataType: "timestamptz", OrdinalPos: 5},
			{Name: "accepted_at", DataType: "timestamptz", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "job_queue", Columns: []introspect.Column{
			{Name: "id", DataType: "bigint", OrdinalPos: 1},
			{Name: "job_type", DataType: "text", OrdinalPos: 2},
			{Name: "payload", DataType: "jsonb", OrdinalPos: 3},
			{Name: "status", DataType: "text", OrdinalPos: 4},
			{Name: "attempts", DataType: "integer", OrdinalPos: 5},
			{Name: "last_error", DataType: "text", OrdinalPos: 6},
			{Name: "scheduled_at", DataType: "timestamptz", OrdinalPos: 7},
			{Name: "completed_at", DataType: "timestamptz", OrdinalPos: 8},
		}},
		{Schema: "public", Name: "oauth_clients", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "name", DataType: "text", OrdinalPos: 2},
			{Name: "client_id", DataType: "text", OrdinalPos: 3},
			{Name: "client_secret", DataType: "text", OrdinalPos: 4},
			{Name: "redirect_uri", DataType: "text", OrdinalPos: 5},
			{Name: "scopes", DataType: "text[]", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "products", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "name", DataType: "text", OrdinalPos: 2},
			{Name: "sku", DataType: "text", OrdinalPos: 3},
			{Name: "price_cents", DataType: "integer", OrdinalPos: 4},
			{Name: "stock_qty", DataType: "integer", OrdinalPos: 5},
			{Name: "category_id", DataType: "integer", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "sessions", Columns: []introspect.Column{
			{Name: "id", DataType: "text", OrdinalPos: 1},
			{Name: "user_id", DataType: "integer", OrdinalPos: 2},
			{Name: "token", DataType: "text", OrdinalPos: 3},
			{Name: "ip_addr", DataType: "inet", OrdinalPos: 4},
			{Name: "user_agent", DataType: "text", OrdinalPos: 5},
			{Name: "expires_at", DataType: "timestamptz", OrdinalPos: 6},
			{Name: "created_at", DataType: "timestamptz", OrdinalPos: 7},
		}},
		{Schema: "public", Name: "tls_certificates", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "domain", DataType: "text", OrdinalPos: 2},
			{Name: "issued_at", DataType: "timestamptz", OrdinalPos: 3},
			{Name: "expires_at", DataType: "timestamptz", OrdinalPos: 4},
			{Name: "issuer", DataType: "text", OrdinalPos: 5},
			{Name: "fingerprint", DataType: "text", OrdinalPos: 6},
		}},
		{Schema: "public", Name: "webhook_endpoints", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
			{Name: "account_id", DataType: "integer", OrdinalPos: 2},
			{Name: "url", DataType: "text", OrdinalPos: 3},
			{Name: "secret_hash", DataType: "text", OrdinalPos: 4},
			{Name: "event_types", DataType: "text[]", OrdinalPos: 5},
			{Name: "is_active", DataType: "boolean", OrdinalPos: 6},
			{Name: "created_at", DataType: "timestamptz", OrdinalPos: 7},
		}},
	}

	cfg := Config{Package: "schema", DotImport: true}
	got, err := Generate(tables, cfg)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	out := string(got)

	// Generated header must be present.
	if !strings.HasPrefix(out, "// Code generated by gosq-codegen; DO NOT EDIT.\n") {
		t.Error("missing generated-file header")
	}

	// All 17 tables must be present.
	tableCount := strings.Count(out, "NewTable(")
	if tableCount != 17 {
		t.Errorf("expected 17 NewTable calls, got %d", tableCount)
	}

	// All 108 columns must be present.
	fieldCount := strings.Count(out, "NewField(")
	if fieldCount != 108 {
		t.Errorf("expected 108 NewField calls, got %d", fieldCount)
	}

	// Tables must be sorted alphabetically: "Accounts" before "Users".
	accountsPos := strings.Index(out, `var Accounts = NewTable("accounts")`)
	usersPos := strings.Index(out, `var Users = NewTable("users")`)
	if accountsPos < 0 {
		t.Error("Accounts table missing from output")
	}
	if usersPos < 0 {
		t.Error("Users table missing from output")
	}
	if accountsPos >= 0 && usersPos >= 0 && accountsPos >= usersPos {
		t.Error("tables not in alphabetical order: Accounts should precede Users")
	}

	// Key naming patterns must produce correct identifiers.
	// go/format aligns = signs within var blocks, so exact "Ident = NewField(...)"
	// checks are fragile. Instead, verify the identifier name and the NewField
	// argument independently — both must be present for the wiring to be correct.
	identChecks := []string{
		"HTTPRequests",        // http initialism
		"HTTPRequestsURLPath", // http + url initialisms
		"TLSCertificates",     // tls initialism
		"TLSCertificatesID",   // tls + id initialisms
		"APIKeys",             // api initialism
		"APIKeysAccountID",    // api + id initialisms
		"AuditLogsIPAddr",     // ip initialism
		"DevicesDeviceUUID",   // uuid initialism
		"Users_2faEnabled",    // digit-prefixed column: 2fa_enabled → _2faEnabled
		"OauthClients",        // oauth is not an initialism — capitalised normally
		"OauthClientsClientID",
		"OauthClientsRedirectURI", // uri initialism
	}
	for _, ident := range identChecks {
		if !strings.Contains(out, ident) {
			t.Errorf("expected identifier %q in output", ident)
		}
	}

	fieldArgChecks := []string{
		`NewField("http_requests.url_path")`,
		`NewField("tls_certificates.id")`,
		`NewField("api_keys.account_id")`,
		`NewField("audit_logs.ip_addr")`,
		`NewField("devices.device_uuid")`,
		`NewField("users.2fa_enabled")`,
		`NewField("oauth_clients.client_id")`,
		`NewField("oauth_clients.redirect_uri")`,
	}
	for _, arg := range fieldArgChecks {
		if !strings.Contains(out, arg) {
			t.Errorf("expected output to contain %q", arg)
		}
	}

	// Output must be deterministic: calling Generate again with the same input
	// must produce identical bytes.
	got2, err := Generate(tables, cfg)
	if err != nil {
		t.Fatalf("second Generate call: unexpected error: %v", err)
	}
	if !bytes.Equal(got, got2) {
		t.Error("Generate is not deterministic: two calls with the same input produced different output")
	}
}

func TestGenerateSingleTable(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "users",
			Columns: []introspect.Column{
				{Name: "id", DataType: "integer", IsNullable: false, OrdinalPos: 1},
				{Name: "name", DataType: "text", IsNullable: false, OrdinalPos: 2},
			},
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Users = NewTable(\"users\")\n\nvar (\n\tUsersID   = NewField(\"users.id\")\n\tUsersName = NewField(\"users.name\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}
