package codegen

import (
	"testing"

	"github.com/libliflin/gosq-codegen/internal/introspect"
)

func TestGenerateEmpty(t *testing.T) {
	out, err := Generate(nil, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n"
	if string(out) != want {
		t.Errorf("output mismatch\ngot:  %q\nwant: %q", string(out), want)
	}
}

func TestGenerateDotImportFalse(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "users",
			Columns: []introspect.Column{
				{Name: "id", DataType: "integer", IsNullable: false, OrdinalPos: 1},
			},
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: false})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport \"github.com/libliflin/gosq\"\n\nvar Users = gosq.NewTable(\"users\")\n\nvar (\n\tUsersID = gosq.NewField(\"users.id\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateDigitLeadingColumn(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "accounts",
			Columns: []introspect.Column{
				{Name: "2fa_enabled", DataType: "boolean", IsNullable: false, OrdinalPos: 1},
			},
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Accounts = NewTable(\"accounts\")\n\nvar (\n\tAccounts_2faEnabled = NewField(\"accounts.2fa_enabled\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateAllUnderscoreColumn(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "items",
			Columns: []introspect.Column{
				{Name: "___", DataType: "text", IsNullable: false, OrdinalPos: 1},
			},
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Items = NewTable(\"items\")\n\nvar (\n\tItems_ = NewField(\"items.___\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateTableNoColumns(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema:  "public",
			Name:    "events",
			Columns: nil,
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Events = NewTable(\"events\")\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateMultipleTablesOrdered(t *testing.T) {
	// Tables deliberately provided out of alphabetical order to verify sort.
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "orders",
			Columns: []introspect.Column{
				{Name: "id", DataType: "integer", IsNullable: false, OrdinalPos: 1},
			},
		},
		{
			Schema: "public",
			Name:   "accounts",
			Columns: []introspect.Column{
				{Name: "id", DataType: "integer", IsNullable: false, OrdinalPos: 1},
			},
		},
	}

	// Empty Package — exercises the default-package fallback.
	got, err := Generate(tables, Config{DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Accounts = NewTable(\"accounts\")\n\nvar (\n\tAccountsID = NewField(\"accounts.id\")\n)\n\nvar Orders = NewTable(\"orders\")\n\nvar (\n\tOrdersID = NewField(\"orders.id\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateTableCollision(t *testing.T) {
	// "user_data" and "user__data" both map to "UserData" — should error.
	tables := []introspect.Table{
		{Schema: "public", Name: "user_data"},
		{Schema: "public", Name: "user__data"},
	}
	_, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err == nil {
		t.Fatal("expected error for colliding table identifiers, got nil")
	}
}

func TestGenerateBlankIdentifierTable(t *testing.T) {
	// A table named "_" (or any all-underscore name) produces toExported → "_",
	// which is the Go blank identifier. var _ = NewTable("_") compiles but the
	// value is discarded and the table can never be referenced. Generate should
	// error rather than silently emit dead code.
	for _, name := range []string{"_", "__", "___"} {
		tables := []introspect.Table{
			{Schema: "public", Name: name},
		}
		_, err := Generate(tables, Config{Package: "schema", DotImport: true})
		if err == nil {
			t.Errorf("expected error for table %q producing blank identifier, got nil", name)
		}
	}
}

func TestGenerateTableFieldCollision(t *testing.T) {
	// Table "users_id" produces table ident "UsersID".
	// Table "users" with column "id" produces field ident "UsersID".
	// Both would emit "var UsersID = ..." — a redeclaration error in the generated file.
	tables := []introspect.Table{
		{Schema: "public", Name: "users", Columns: []introspect.Column{
			{Name: "id", DataType: "integer", OrdinalPos: 1},
		}},
		{Schema: "public", Name: "users_id"},
	}
	_, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err == nil {
		t.Fatal("expected error for table-field identifier collision, got nil")
	}
}

func TestGenerateCrossTableFieldCollision(t *testing.T) {
	// Table "a" with column "b_c" produces field var "A"+"BC" = "ABC".
	// Table "a_b" with column "c" produces field var "AB"+"C" = "ABC".
	// Table collision detection passes (A ≠ AB), within-table column detection
	// passes (each table has one column), but the full field identifiers collide.
	tables := []introspect.Table{
		{Schema: "public", Name: "a", Columns: []introspect.Column{
			{Name: "b_c", DataType: "text", OrdinalPos: 1},
		}},
		{Schema: "public", Name: "a_b", Columns: []introspect.Column{
			{Name: "c", DataType: "text", OrdinalPos: 1},
		}},
	}
	_, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err == nil {
		t.Fatal("expected error for cross-table field identifier collision, got nil")
	}
}

func TestGenerateColumnCollision(t *testing.T) {
	// "my_field" and "my__field" both map to "MyField" — should error.
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "items",
			Columns: []introspect.Column{
				{Name: "my_field", DataType: "text", OrdinalPos: 1},
				{Name: "my__field", DataType: "text", OrdinalPos: 2},
			},
		},
	}
	_, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err == nil {
		t.Fatal("expected error for colliding column identifiers, got nil")
	}
}

func TestToExported(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		// Single words
		{"name", "Name"},
		{"id", "ID"},
		{"url", "URL"},
		{"uri", "URI"},
		{"uuid", "UUID"},
		{"ip", "IP"},
		{"api", "API"},
		{"sql", "SQL"},
		{"json", "JSON"},
		{"xml", "XML"},
		{"rpc", "RPC"},
		{"tls", "TLS"},
		{"ttl", "TTL"},
		{"http", "HTTP"},
		{"https", "HTTPS"},
		{"uid", "UID"},
		{"io", "IO"},
		{"cpu", "CPU"},

		// Compound snake_case
		{"user_id", "UserID"},
		{"url_params", "URLParams"},
		{"created_at", "CreatedAt"},
		{"updated_at", "UpdatedAt"},
		{"http_status_code", "HTTPStatusCode"},
		{"api_key", "APIKey"},
		{"oauth_token", "OauthToken"},

		// Edge cases
		{"2fa_enabled", "_2faEnabled"},
		{"___", "_"},
		{"", "_"},
		{"_leading", "Leading"},
		{"trailing_", "Trailing"},

		// Non-ASCII: column starting with a multi-byte UTF-8 character
		{"éclat", "Éclat"},
	}

	for _, tc := range tests {
		t.Run(tc.in, func(t *testing.T) {
			got := toExported(tc.in)
			if got != tc.want {
				t.Errorf("toExported(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestGenerateSingleTable(t *testing.T) {
	tables := []introspect.Table{
		{
			Schema: "public",
			Name:   "users",
			Columns: []introspect.Column{
				{Name: "id", DataType: "integer", IsNullable: false, OrdinalPos: 1},
				{Name: "name", DataType: "text", IsNullable: false, OrdinalPos: 2},
			},
		},
	}

	got, err := Generate(tables, Config{Package: "schema", DotImport: true})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := "// Code generated by gosq-codegen; DO NOT EDIT.\n\npackage schema\n\nimport . \"github.com/libliflin/gosq\"\n\nvar Users = NewTable(\"users\")\n\nvar (\n\tUsersID   = NewField(\"users.id\")\n\tUsersName = NewField(\"users.name\")\n)\n"
	if string(got) != want {
		t.Errorf("output mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}
